name: face_camera
description: A Flutter camera plugin that detects faces in real-time. In addition it can capture automatically once a face is detected, This can be handy while taking a selfie during kyc.
version: 0.1.4

environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  # Camera
  camera: ^0.11.0+2

  # ML Kit
  google_mlkit_face_detection: 0.11.1

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.conezi.face_camera
        pluginClass: FaceCameraPlugin
      ios:
        pluginClass: FaceCameraPlugin